name: 猫步旅人的博客
description: Coding, Startups and Ideas
meta_description: "关注技术，钻研技术，崇尚技术"
email: hytwzy@163.com

markdown: kramdown
#highlighter: pygments
#github does not support pygments now, change to rouge
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'wuzhenyu.com.cn'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url: 'https://small-cat.github.io'
author: '吴震宇'

# sidebar settings
sidebar: true
sidebar-about-description: "不要被信息的伪高潮所淹没，而自以为是在学习和进步"
sidebar-avatar:

# SNS settings
github_username: small-cat
